version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - mongo-node-network

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-node-network

networks:
  mongo-node-network:
    driver: bridge

